name: Qodana
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1,3,5'
  pull_request:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
      checks: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          submodules: recursive
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'
          dotnet-quality: 'ga'
      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        continue-on-error: true
        with:
          args: --ide,QDNET
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Upload Qodana SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        continue-on-error: true
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
